//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pagos
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.servicios.co/pagos/service", ConfigurationName="pagos.PagosInerface")]
    public interface PagosInerface
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<pagos.CosultarResponse> CosultarAsync(pagos.CosultarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="pagar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<pagos.PagarResponse> PagarAsync(pagos.PagarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="compensar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<pagos.PagarResponse> CompensarAsync(pagos.PagarRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.servicios.co/pagos/schemas")]
    public partial class ReferenciaFactura
    {
        
        private string referenciaFacturaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string referenciaFactura
        {
            get
            {
                return this.referenciaFacturaField;
            }
            set
            {
                this.referenciaFacturaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.servicios.co/pagos/schemas")]
    public partial class Resultado
    {
        
        private ReferenciaFactura referenciaFacturaField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ReferenciaFactura referenciaFactura
        {
            get
            {
                return this.referenciaFacturaField;
            }
            set
            {
                this.referenciaFacturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.servicios.co/pagos/schemas")]
    public partial class Pago
    {
        
        private ReferenciaFactura referenciaFacturaField;
        
        private double totalPagarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ReferenciaFactura referenciaFactura
        {
            get
            {
                return this.referenciaFacturaField;
            }
            set
            {
                this.referenciaFacturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double totalPagar
        {
            get
            {
                return this.totalPagarField;
            }
            set
            {
                this.totalPagarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.servicios.co/pagos/schemas")]
    public partial class ResultadoConsulta
    {
        
        private ReferenciaFactura referenciaFacturaField;
        
        private double totalPagarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ReferenciaFactura referenciaFactura
        {
            get
            {
                return this.referenciaFacturaField;
            }
            set
            {
                this.referenciaFacturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double totalPagar
        {
            get
            {
                return this.totalPagarField;
            }
            set
            {
                this.totalPagarField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CosultarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.servicios.co/pagos/schemas", Order=0)]
        public pagos.ReferenciaFactura ReferenciaFactura;
        
        public CosultarRequest()
        {
        }
        
        public CosultarRequest(pagos.ReferenciaFactura ReferenciaFactura)
        {
            this.ReferenciaFactura = ReferenciaFactura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CosultarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.servicios.co/pagos/schemas", Order=0)]
        public pagos.ResultadoConsulta ResultadoConsulta;
        
        public CosultarResponse()
        {
        }
        
        public CosultarResponse(pagos.ResultadoConsulta ResultadoConsulta)
        {
            this.ResultadoConsulta = ResultadoConsulta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.servicios.co/pagos/schemas", Order=0)]
        public pagos.Pago Pago;
        
        public PagarRequest()
        {
        }
        
        public PagarRequest(pagos.Pago Pago)
        {
            this.Pago = Pago;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.servicios.co/pagos/schemas", Order=0)]
        public pagos.Resultado Resultado;
        
        public PagarResponse()
        {
        }
        
        public PagarResponse(pagos.Resultado Resultado)
        {
            this.Resultado = Resultado;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface PagosInerfaceChannel : pagos.PagosInerface, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class PagosInerfaceClient : System.ServiceModel.ClientBase<pagos.PagosInerface>, pagos.PagosInerface
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PagosInerfaceClient() : 
                base(PagosInerfaceClient.GetDefaultBinding(), PagosInerfaceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Pagos.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PagosInerfaceClient(EndpointConfiguration endpointConfiguration) : 
                base(PagosInerfaceClient.GetBindingForEndpoint(endpointConfiguration), PagosInerfaceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PagosInerfaceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PagosInerfaceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PagosInerfaceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PagosInerfaceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PagosInerfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<pagos.CosultarResponse> pagos.PagosInerface.CosultarAsync(pagos.CosultarRequest request)
        {
            return base.Channel.CosultarAsync(request);
        }
        
        public System.Threading.Tasks.Task<pagos.CosultarResponse> CosultarAsync(pagos.ReferenciaFactura ReferenciaFactura)
        {
            pagos.CosultarRequest inValue = new pagos.CosultarRequest();
            inValue.ReferenciaFactura = ReferenciaFactura;
            return ((pagos.PagosInerface)(this)).CosultarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<pagos.PagarResponse> pagos.PagosInerface.PagarAsync(pagos.PagarRequest request)
        {
            return base.Channel.PagarAsync(request);
        }
        
        public System.Threading.Tasks.Task<pagos.PagarResponse> PagarAsync(pagos.Pago Pago)
        {
            pagos.PagarRequest inValue = new pagos.PagarRequest();
            inValue.Pago = Pago;
            return ((pagos.PagosInerface)(this)).PagarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<pagos.PagarResponse> pagos.PagosInerface.CompensarAsync(pagos.PagarRequest request)
        {
            return base.Channel.CompensarAsync(request);
        }
        
        public System.Threading.Tasks.Task<pagos.PagarResponse> CompensarAsync(pagos.Pago Pago)
        {
            pagos.PagarRequest inValue = new pagos.PagarRequest();
            inValue.Pago = Pago;
            return ((pagos.PagosInerface)(this)).CompensarAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Pagos))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Pagos))
            {
                return new System.ServiceModel.EndpointAddress("http://desktop-3a7qup7:8088/mockServicioPagos");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PagosInerfaceClient.GetBindingForEndpoint(EndpointConfiguration.Pagos);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PagosInerfaceClient.GetEndpointAddress(EndpointConfiguration.Pagos);
        }
        
        public enum EndpointConfiguration
        {
            
            Pagos,
        }
    }
}
